### RAIZ DO PROJETO
GET http://localhost:5219

### LISTAR PRODUTOS
GET http://localhost:5219/api/produto/listar

### BUSCAR PRODUTO
GET http://localhost:5219/api/produto/buscar/Mou

### CADASTRAR PRODUTO
POST http://localhost:5219/api/produto/cadastrar
Content-Type: application/json

{
    "Nome": "Mouse",
    "Valor": 75.99
}

### ATUALIZAR PRODUTO
PUT http://localhost:5219/api/produto/atualizar/Teclado
Content-Type: application/json

{
    "Nome": "Teclado Gamer"
}

### DELETAR PRODUTO
DELETE http://localhost:5219/api/produto/deletar/Teclado%20Gamer